<x-layouts.public title="Terms &amp; Conditions" metaDescription="Terms and Conditions for James Gifford's AI Professional Assistant at jamesgifford.ai">
    <div class="max-w-[720px] mx-auto px-6 py-8 pb-20">
        <a href="{{ route('home') }}" class="inline-flex items-center gap-1.5 text-sm text-zinc-500 hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors mb-8">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                <path fill-rule="evenodd" d="M17 10a.75.75 0 0 1-.75.75H5.612l4.158 3.96a.75.75 0 1 1-1.04 1.08l-5.5-5.25a.75.75 0 0 1 0-1.08l5.5-5.25a.75.75 0 1 1 1.04 1.08L5.612 9.25H16.25A.75.75 0 0 1 17 10Z" clip-rule="evenodd" />
            </svg>
            Back to chat
        </a>

        <article class="prose prose-zinc dark:prose-invert max-w-none prose-headings:font-semibold prose-h1:text-3xl prose-h1:mb-2 prose-h2:text-xl prose-h2:mt-10 prose-h2:mb-4 prose-p:leading-[1.75] prose-li:leading-[1.75] prose-a:text-emerald-600 dark:prose-a:text-emerald-400 prose-strong:text-zinc-900 dark:prose-strong:text-zinc-100">
            <h1>Terms &amp; Conditions</h1>
            <p class="text-zinc-500 dark:text-zinc-400 text-sm !mt-1 !mb-10">Last updated: March 22, 2026</p>

            <h2>Overview</h2>
            <p>This website (jamesgifford.ai) provides an AI-powered professional assistant that represents James Gifford in conversations with potential employers, recruiters, and hiring managers. By using this service via the web chat, email, or SMS, you agree to the following terms.</p>
            <p>The service is operated by Progravity LLC, an Oregon-based software company.</p>

            <h2>Nature of the Service</h2>
            <p>This is an <strong>automated AI assistant</strong>, not a human. Responses are generated by large language models based on professional information provided by James Gifford. While we strive for accuracy, the assistant may occasionally produce incorrect or incomplete information.</p>
            <p>The assistant's responses do not constitute legally binding commitments, contractual offers, or professional advice of any kind. Any hiring decisions, salary negotiations, or employment agreements must be made directly with James Gifford.</p>

            <h2>Acceptable Use</h2>
            <p>You agree to use this service only for legitimate professional inquiries related to James Gifford's background, skills, and availability. You agree not to:</p>
            <ul>
                <li>Attempt to extract personal information beyond what the assistant is designed to share</li>
                <li>Send abusive, threatening, or harassing messages</li>
                <li>Use automated tools to send high volumes of messages</li>
                <li>Attempt to manipulate the AI into producing harmful, misleading, or inappropriate content</li>
                <li>Use the service for any illegal purpose</li>
            </ul>
            <p>We reserve the right to block users who violate these terms without notice.</p>

            <h2>SMS Terms</h2>
            <p>By texting our SMS number, you agree to receive automated AI-generated replies in response to your messages.</p>
            <ul>
                <li><strong>Opt-in</strong>: You opt in by sending the first text message to our number.</li>
                <li><strong>Opt-out</strong>: Reply <strong>STOP</strong> at any time to stop receiving messages.</li>
                <li><strong>Help</strong>: Reply <strong>HELP</strong> for assistance information.</li>
                <li><strong>Message frequency</strong>: Varies — we only respond to messages you initiate.</li>
                <li><strong>Message and data rates</strong>: May apply depending on your mobile carrier and plan.</li>
                <li><strong>Carriers</strong>: Compatible with all major US carriers.</li>
            </ul>
            <p>We do not send unsolicited messages, marketing content, or promotional material.</p>

            <h2>Intellectual Property</h2>
            <p>The content and design of this website and the AI assistant's system are the property of Progravity LLC. The professional information shared by the assistant about James Gifford is provided with his authorization.</p>

            <h2>Limitation of Liability</h2>
            <p>This service is provided "as is" without warranties of any kind, express or implied. Progravity LLC and James Gifford are not liable for any damages arising from your use of this service, including but not limited to:</p>
            <ul>
                <li>Inaccurate or incomplete information provided by the AI assistant</li>
                <li>Service interruptions or technical failures</li>
                <li>Actions taken based on information provided by the assistant</li>
            </ul>

            <h2>Data and Privacy</h2>
            <p>Your use of this service is also governed by our <a href="{{ route('privacy') }}">Privacy Policy</a>. By using the service, you acknowledge that you have read and understand our Privacy Policy.</p>

            <h2>Rate Limiting</h2>
            <p>To ensure fair use and manage costs, the service enforces rate limits on the number of messages you can send per hour and per day. If you exceed these limits, you will be notified and can try again later.</p>

            <h2>Modifications</h2>
            <p>We may update these Terms &amp; Conditions at any time. Changes will be reflected by updating the "Last updated" date at the top of this page. Continued use of the service after changes constitutes acceptance of the updated terms.</p>

            <h2>Governing Law</h2>
            <p>These terms are governed by the laws of the State of Oregon, United States.</p>

            <h2>Contact</h2>
            <p>
                For questions about these Terms &amp; Conditions, contact:<br>
                James Gifford<br>
                Progravity LLC<br>
                <a href="mailto:james@jamesgifford.com">james@jamesgifford.com</a>
            </p>
        </article>
    </div>
</x-layouts.public>
